# Chapter 1

## Exercise (P15)
[参考](https://datascience.stackexchange.com/questions/6639/extra-output-layer-in-a-neural-network-decimal-to-binary)

In [1]:
import numpy as np

In [56]:
W2 = np.zeros((4,10))
A2 = np.array([
        [0.991,0.007,0.006,0.008,0.007,0.008,0.007,0.008,0.007,0.008], # 0
        [0.008,0.991,0.003,0.008,0.007,0.008,0.007,0.008,0.007,0.008], # 1
        [0.008,0.007,0.991,0.008,0.007,0.008,0.007,0.008,0.007,0.008], # 2
        [0.008,0.007,0.008,0.991,0.007,0.008,0.007,0.008,0.007,0.008], # 3
        [0.008,0.007,0.008,0.007,0.991,0.008,0.007,0.008,0.007,0.008], # 4
        [0.008,0.007,0.008,0.007,0.008,0.991,0.007,0.008,0.007,0.008], # 5
        [0.008,0.007,0.008,0.007,0.008,0.007,0.991,0.008,0.007,0.008], # 6
        [0.008,0.007,0.008,0.007,0.008,0.007,0.008,0.991,0.007,0.008], # 7
        [0.008,0.007,0.008,0.007,0.008,0.007,0.008,0.007,0.991,0.008], # 8
        [0.008,0.007,0.008,0.007,0.008,0.007,0.008,0.007,0.008,0.991,]  # 9
    ]) # 
A2_3 = np.array([0.008,0.007,0.008,0.991,0.007,0.008,0.007,0.008,0.007,0.008])

In [57]:
print("W2.shape:",W2.shape)
print("A2.shape:",A2.shape)

W2.shape: (4, 10)
A2.shape: (10, 10)


## Binary Schema
$$
[
  [0,0,0,0],
  [0,0,0,1],
  [0,0,1,0],
  [0,0,1,1],
  [0,1,0,0],
  [0,1,0,1],
  [0,1,1,0],
  [0,1,1,1],
  [1,0,0,0],
  [1,0,0,1]
]
$$

In [58]:
# 0 
W2[:,0] = -10

# 1
W2[0][1] = -10
W2[1][1] = -10
W2[2][1] = -10
W2[3][1] = 10

# 2
W2[0][2] = -10
W2[1][2] = -10
W2[2][2] = 10
W2[3][2] = -10

# 3
W2[0][3] = -10
W2[1][3] = -10
W2[2][3] = 10
W2[3][3] = 10

# 4
W2[0][4] = -10
W2[1][4] = 10
W2[2][4] = -10
W2[3][4] = -10

# 5
W2[0][5] = -10
W2[1][5] = 10
W2[2][5] = -10
W2[3][5] = 10

# 6
W2[0][6] = -10
W2[1][6] = 10
W2[2][6] = 10
W2[3][6] = -10

# 7
W2[0][7] = -10
W2[1][7] = 10
W2[2][7] = 10
W2[3][7] = 10

# 8
W2[0][8] = 10
W2[1][8] = -10
W2[2][8] = -10
W2[3][8] = -10

# 9
W2[0][9] = 10
W2[1][9] = -10
W2[2][9] = -10
W2[3][9] = 10

In [59]:
W2

array([[-10., -10., -10., -10., -10., -10., -10., -10.,  10.,  10.],
       [-10., -10., -10., -10.,  10.,  10.,  10.,  10., -10., -10.],
       [-10., -10.,  10.,  10., -10., -10.,  10.,  10., -10., -10.],
       [-10.,  10., -10.,  10., -10.,  10., -10.,  10., -10.,  10.]])

In [60]:
Z3 = np.dot(A2,W2.T)

In [61]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [62]:
A3 = sigmoid(Z3)

In [63]:
A3

array([[3.46561743e-05, 4.67803750e-05, 4.58541039e-05, 5.60057605e-05],
       [3.53562507e-05, 4.77253561e-05, 4.40562180e-05, 9.99950327e-01],
       [3.39699594e-05, 4.58541039e-05, 9.99938104e-01, 5.48968330e-05],
       [3.39699594e-05, 4.58541039e-05, 9.99938104e-01, 9.99947256e-01],
       [3.39699594e-05, 9.99938104e-01, 4.58541039e-05, 5.38098613e-05],
       [3.39699594e-05, 9.99938104e-01, 4.58541039e-05, 9.99946190e-01],
       [3.39699594e-05, 9.99938104e-01, 9.99938104e-01, 5.27444109e-05],
       [3.39699594e-05, 9.99938104e-01, 9.99938104e-01, 9.99945103e-01],
       [9.99916452e-01, 4.58541039e-05, 4.58541039e-05, 5.17000556e-05],
       [9.99916452e-01, 4.58541039e-05, 4.58541039e-05, 9.99943994e-01]])

In [64]:
A3[A3 >= 0.5] = 1
A3[A3 < 0.5] = 0

In [65]:
A3

array([[0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.]])